# Generated by Django 5.1.7 on 2025-03-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnUniversitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('an_start', models.IntegerField()),
                ('an_end', models.IntegerField()),
            ],
        ),
    ]
