# Generated by Django 5.1.7 on 2025-03-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('departament', models.CharField(choices=[('IT', 'IT'), ('M', 'Medicina'), ('L', 'Litere'), ('D', 'Drept')], max_length=30)),
            ],
        ),
    ]
