# Generated by Django 5.1.7 on 2025-03-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AnUnivApp", "0001_initial"),
        ("ProfesoriApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profesori",
            name="an_universitae",
            field=models.ManyToManyField(to="AnUnivApp.anuniversitar"),
        ),
    ]
