# Generated by Django 5.1.7 on 2025-04-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProfesoriApp", "0003_profesori_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profesori",
            name="salary",
            field=models.FloatField(default=4000),
        ),
    ]
