# Generated by Django 5.1.7 on 2025-04-04 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ProfesoriApp", "0004_alter_profesori_salary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profesori",
            old_name="an_universitae",
            new_name="an_universitar",
        ),
    ]
