# Generated by Django 5.1.7 on 2025-03-22 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AnUnivApp', '0001_initial'),
        ('ProfesoriApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('an_universitar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnUnivApp.anuniversitar')),
                ('profesori', models.ManyToManyField(blank=True, to='ProfesoriApp.profesori')),
                ('tutore', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutore_student', to='ProfesoriApp.profesori')),
            ],
        ),
    ]
