# Generated by Django 5.1.7 on 2025-03-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('content', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('O', 'Open'), ('C', 'Completed'), ('IP', 'In Progress')], max_length=20)),
                ('type', models.CharField(choices=[('B', 'Business'), ('D', 'Diplomacy'), ('L', 'Leadership'), ('T', 'Trolling')], max_length=20)),
                ('due_date', models.DateField()),
                ('create_date', models.DateField()),
            ],
        ),
    ]
