# Generated by Django 5.1.7 on 2025-03-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TaskApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('image', models.TextField(blank=True, null=True)),
                ('tasks', models.ManyToManyField(blank=True, null=True, to='TaskApp.task')),
            ],
        ),
    ]
